### ISSUE TITLE
Setup CI and integration tests

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/ocid#16]

**Comment by mrunalp** [comment]
We need @sarahnovotny or @vishh or @yujuhong to help set up travis integration.

**Comment by runcom** [comment]
we need this in order to check for DCO also (lint, and other little stuff)

**Comment by vishh** [comment]
What is needed @mrunalp? We also have a jenkins test server we maintain for
k8s. So depending on the testing needs, we can use jenkins or travis.

**Comment by mrunalp** [comment]
@vishh Right now travis will suffice. I will let you know when we are ready for jenkins :)
For now, you need to sign into travis with github creds and turn on the tests for this repo. See https://docs.travis-ci.com/user/getting-started/. Thanks!
