### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by cyphar** [kubernetes-incubator/ocid#18]
To be fair, I have an unconventional `GOPATH` setup (I have my home directory set to be my `GOPATH` then I put all projects under `~/src/project` with a symlink at `~/src/github.com/*` to `~/src`. The idea being that I don't need to have the three-level-deep project hierarchy that is mandated by Go.

However, running `make` causes this interesting error:

```
go build -o ocid ./cmd/server/main.go
# command-line-arguments
cmd/server/main.go:62: cannot use service (type *server.Server) as type "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RuntimeServiceServer in argument to "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RegisterRuntimeServiceServer:
        *server.Server does not implement "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RuntimeServiceServer (wrong type for ContainerStatus method)
                have ContainerStatus("github.com/kubernetes-incubator/ocid/vendor/golang.org/x/net/context".Context, *"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusRequest) (*"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusResponse, error)
                want ContainerStatus("ocid/vendor/golang.org/x/net/context".Context, *"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusRequest) (*"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusResponse, error)
cmd/server/main.go:63: cannot use service (type *server.Server) as type "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageServiceServer in argument to "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RegisterImageServiceServer:
        *server.Server does not implement "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageServiceServer (wrong type for ImageStatus method)
                have ImageStatus("github.com/kubernetes-incubator/ocid/vendor/golang.org/x/net/context".Context, *"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusRequest) (*"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusResponse, error)
                want ImageStatus("ocid/vendor/golang.org/x/net/context".Context, *"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusRequest) (*"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusResponse, error)
make: *** [Makefile:6: ocid] Error 2
make  24.54s user 1.05s system 598% cpu 4.277 total
```

From what I can see, it looks like my Go install appears to be getting the wrong type for `golang.org/x/net/context.Context` and instead appends a `github.com/kubernetes-incubator` to the type name. Here's my Go version -- would Go 1.7 fix this problem?

```
% go version
go version go1.6.3 linux/amd64
```

**Comment by runcom** [comment]
I know what this is and the root cause is that godeps sucks in my opinion because it vendors from GOPATH and vendoring is complicated because you don't really check every revisions in your GOPATH before running godeps and the results is that most packages don't get even vendored in the json :) I have a PR almost ready to switch to a saner vendoring tool like glide

**Comment by runcom** [comment]
BTW, my rant against godep could not be related to this issue, but worth a try.

**Comment by mrunalp** [comment]
I agree that godep doesn't work half the time. 👍 on moving to anything better!

**Comment by runcom** [comment]
opened https://github.com/kubernetes-incubator/ocid/pull/19 to move to glide

**Comment by cyphar** [comment]
Why not use https://github.com/LK4D4/vndr? The thing I like about the Docker `vendor.sh` script is that it is very simple and there's no funny business with your vendoring tool trying to "update" your dependencies automatically.

**Comment by runcom** [comment]
> Why not use https://github.com/LK4D4/vndr? The thing I like about the Docker vendor.sh script is that it is very simple and there's no funny business with your vendoring tool trying to "update" your dependencies automatically.

@cyphar I believe they're the same, opencontainers/image-spec and image-tools use glide w/o hassles - I believe it's really the same, any reason you want `vndr`?

also does #19 fix your issue here?

**Comment by cyphar** [comment]
It doesn't fix the problem. And if you think that glade is fine I don't really care all that much (anything is better than godep):

```
make -C conmon
make[1]: Entering directory '/home/cyphar/src/ocid/conmon'
cc -Wall -Wextra -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -c -o conmon.o conmon.c
cc -o conmon conmon.o -lglib-2.0
make[1]: Leaving directory '/home/cyphar/src/ocid/conmon'
go build -o ocid ./cmd/server/main.go
# command-line-arguments
cmd/server/main.go:62: cannot use service (type *server.Server) as type "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RuntimeServiceServer in argument to "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RegisterRuntimeServiceServer:
        *server.Server does not implement "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RuntimeServiceServer (wrong type for ContainerStatus method)
                have ContainerStatus("github.com/kubernetes-incubator/ocid/vendor/golang.org/x/net/context".Context, *"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusRequest) (*"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusResponse, error)
                want ContainerStatus("ocid/vendor/golang.org/x/net/context".Context, *"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusRequest) (*"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ContainerStatusResponse, error)
cmd/server/main.go:63: cannot use service (type *server.Server) as type "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageServiceServer in argument to "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".RegisterImageServiceServer:
        *server.Server does not implement "ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageServiceServer (wrong type for ImageStatus method)
                have ImageStatus("github.com/kubernetes-incubator/ocid/vendor/golang.org/x/net/context".Context, *"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusRequest) (*"github.com/kubernetes-incubator/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusResponse, error)
                want ImageStatus("ocid/vendor/golang.org/x/net/context".Context, *"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusRequest) (*"ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime".ImageStatusResponse, error)
make: *** [Makefile:9: ocid] Error 2
make  23.28s user 1.06s system 421% cpu 5.780 total

```

**Comment by runcom** [comment]
> It doesn't fix the problem. And if you think that glade is fine I don't really care all that much (anything is better than godep):

lol right, on my end it's really easy to switch to `vndr` so if you find glide too much or it won't work for our usual vendoring somehow - feel free to replace it.

> It doesn't fix the problem.

ouch, I should try with your setup running golang from master (normally i use 1.6.3 and I don't have this issue). Out of curiosity, would you try not having that symlink and see if this issue persist?

**Comment by cyphar** [comment]
Yeah, I'll give that a shot. I _really_ hope that I don't need to switch to Go's preposterous ideas about how a home directory should be organised.

**Comment by cyphar** [comment]
Yeah, not using the symlink fixes the issue. **facepalm** This is utterly ludicrous, and my guess the reason this is happening is because of the vendoring experiment changes not being properly written -- maybe I should write a patch for Go to fix this.

**Comment by cyphar** [comment]
I'll close this issue since it's technically on my end. A possible solution would be for us to create a Dockerfile which allows us to build the binaries.

**Comment by runcom** [comment]
> create a Dockerfile which allows us to build the binaries.

:+1: could you file an issue so we won't forget and anyone can pick that up and contribute?

**Comment by q384566678** [comment]
Hello, I also encountered a similar problem, I would like to ask you how to solve the problem

go build -o ocid ./cmd/server/main.go
# command-line-arguments
cmd/server/main.go:99: cannot use s (type *grpc.Server) as type *grpc.Server in argument to runtime.RegisterRuntimeServiceServer
cmd/server/main.go:99: cannot use service (type *server.Server) as type runtime.RuntimeServiceServer in argument to runtime.RegisterRuntimeServiceServer:
	*server.Server does not implement runtime.RuntimeServiceServer (wrong type for ContainerStatus method)
		have ContainerStatus(context.Context, *runtime.ContainerStatusRequest) (*runtime.ContainerStatusResponse, error)
		want ContainerStatus(context.Context, *runtime.ContainerStatusRequest) (*runtime.ContainerStatusResponse, error)
