### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/ocid#38]
We need some basic integration tests that we can run per PR. `bats` could be used if there are no suggestions for anything better. 
cc: @runcom

**Comment by runcom** [comment]
Let's leave this open and close https://github.com/kubernetes-incubator/ocid/issues/16 then, I'll try to work on this as soon as I can if anyone doesn't jump here and take this :)

**Comment by mrunalp** [comment]
Sounds good! :)
