### ISSUE TITLE
repo description is wrong

### ISSUE THREAD

**Issue by runcom** [kubernetes-incubator/ocid#9]
a silly one - but the repo description is saying

> Open Container Image Format integration to Kubernetes

while I think it should be

> Open Container Initiative integration to Kubernetes

**Comment by mrunalp** [comment]
@sarahnovotny @vishh Could one of you help fix this? Thanks!

**Comment by philips** [comment]
I can.

**Comment by philips** [comment]
Does this work? "An Open Container Initiative Runtime Integration to Kubernetes"

**Comment by runcom** [comment]
> "An Open Container Initiative Runtime Integration to Kubernetes"

fine with me :)

**Comment by mrunalp** [comment]
I would prefer not to have runtime in the description, since we intend to add support for oci images as well.
How about "Open Container Initiative Integration to Kubernetes" ? (like @runcom first suggested).

**Comment by philips** [comment]
Would it make sense to use the tagline from the README? "Open Container Initiative-based implementation of Kubernetes Container Runtime Interface"?

https://github.com/kubernetes-incubator/ocid#ocid---oci-based-implementation-of-kubernetes-container-runtime-interface

I am trying to balance the fact that other engines will also do OCI, for example Docker is probably just as OCI as ocid as they both use runC.

**Comment by mrunalp** [comment]
@philips Yeah, sure. The README description works fine. Thanks!

**Comment by sarahnovotny** [comment]
LGTM
